<#
.SYNOPSIS
    Bumps a vendored vcpkg dependency to a new upstream version.

.DESCRIPTION
    This script automates the mechanical parts of updating a vendored vcpkg
    dependency in this repository. It is normally invoked through the
    `update-vcpkg-port` skill (.github/skills/update-vcpkg-port/SKILL.md),
    which adds the orchestration and decision logic around it.

    For all supported ports it updates the matching entry in
    contrib/win32/openssh/vcpkg.json `overrides[]`. Optionally bumps the
    `builtin-baseline`.

    For overlay ports (libressl, libfido2) it additionally:
    - Updates contrib/win32/openssh/vcpkg_overlay_ports/<port>/vcpkg.json
      `version`.
    - Downloads the new source archive, computes its SHA512, and rewrites
      the SHA512 line in portfile.cmake.

    For libressl it additionally rewrites FILEVERSION / PRODUCTVERSION /
    "FileVersion" / "ProductVersion" in
    vcpkg_overlay_ports/libressl/add-version-file.patch so the
    cross-check enforced by Install-VcpkgDependencies.ps1 stays green.

    Patch *re-application* is intentionally NOT automated. After this tool
    runs, invoke Install-VcpkgDependencies.ps1; if vcpkg reports a
    rejected hunk, the patch must be regenerated by hand. The skill walks
    the user through that decision tree.

.PARAMETER Port
    One of: libressl, libfido2, zlib, libcbor.

.PARAMETER Version
    New target version (e.g. '4.3.0', '1.17.0').

.PARAMETER SourceUrl
    Optional explicit URL to download the source archive from. Required
    only if the port's existing portfile.cmake doesn't expose a derivable
    URL for the new version (rare).

.PARAMETER Baseline
    Optional new value for vcpkg.json `builtin-baseline`. If omitted, the
    baseline is left untouched.

.PARAMETER DryRun
    Print all planned changes without modifying any files.

.OUTPUTS
    Returns a hashtable with:
    - Success: Boolean
    - Port: Port name
    - OldVersion / NewVersion
    - FilesChanged: Array of file paths that would be / were modified
    - Sha512: Computed SHA512 (overlay ports only)
    - LibresslPatchUpdated: Boolean (libressl only)
    - DryRun: Boolean
    - Errors: Array of error strings
    - Message: Summary message

.EXAMPLE
    .\Update-VcpkgPort.ps1 -Port libfido2 -Version 1.17.0 -DryRun

    Show what changes would be made for a libfido2 bump.

.EXAMPLE
    .\Update-VcpkgPort.ps1 -Port libressl -Version 4.3.0

    Bump libressl, refresh SHA512, update add-version-file.patch, write
    files to disk. Validate afterwards with Install-VcpkgDependencies.ps1.

.NOTES
    - Network access required for overlay ports (downloads source archive).
    - Does NOT run vcpkg install. Validate by running
      Install-VcpkgDependencies.ps1 after this tool succeeds.
    - Always run on a clean working tree so the diff is easy to review.
#>

param(
    [Parameter(Mandatory=$true)]
    [ValidateSet('libressl', 'libfido2', 'zlib', 'libcbor')]
    [string]$Port,

    [Parameter(Mandatory=$true)]
    [string]$Version,

    [Parameter(Mandatory=$false)]
    [string]$SourceUrl,

    [Parameter(Mandatory=$false)]
    [string]$Baseline,

    [Parameter(Mandatory=$false)]
    [switch]$DryRun
)

$ErrorActionPreference = 'Stop'

$scriptRoot = $PSScriptRoot
if ([string]::IsNullOrEmpty($scriptRoot)) {
    $scriptRoot = Split-Path -Parent $MyInvocation.MyCommand.Path
}
$repoRoot = (Get-Item $scriptRoot).Parent.Parent.FullName
$opensshDir = Join-Path $repoRoot 'contrib\win32\openssh'
$manifestPath = Join-Path $opensshDir 'vcpkg.json'
$overlayPortsDir = Join-Path $opensshDir 'vcpkg_overlay_ports'
$overlayPortDir = Join-Path $overlayPortsDir $Port
$overlayManifestPath = Join-Path $overlayPortDir 'vcpkg.json'
$overlayPortfilePath = Join-Path $overlayPortDir 'portfile.cmake'
$libresslPatchPath = Join-Path $overlayPortsDir 'libressl\add-version-file.patch'

$result = @{
    Success = $false
    Port = $Port
    OldVersion = $null
    NewVersion = $Version
    FilesChanged = @()
    Sha512 = $null
    LibresslPatchUpdated = $false
    DryRun = [bool]$DryRun
    Errors = @()
    Message = ''
}

function Get-PortDownloadUrl {
    param([string]$Port, [string]$Version, [string]$Override)

    if (-not [string]::IsNullOrWhiteSpace($Override)) {
        return $Override
    }
    switch ($Port) {
        'libressl' { return "https://ftp.openbsd.org/pub/OpenBSD/LibreSSL/libressl-$Version.tar.gz" }
        'libfido2' { return "https://github.com/Yubico/libfido2/archive/refs/tags/$Version.tar.gz" }
        default    { return $null }
    }
}

function Get-Sha512OfUrl {
    param([string]$Url)

    $tmp = New-TemporaryFile
    try {
        Write-Host "    Downloading $Url" -ForegroundColor Gray
        Invoke-WebRequest -Uri $Url -OutFile $tmp.FullName -UseBasicParsing
        $hash = (Get-FileHash -Path $tmp.FullName -Algorithm SHA512).Hash
        return $hash.ToLowerInvariant()
    } finally {
        Remove-Item -LiteralPath $tmp.FullName -Force -ErrorAction SilentlyContinue
    }
}

function Update-JsonFile {
    param(
        [string]$Path,
        [scriptblock]$Mutator
    )

    $raw = Get-Content -LiteralPath $Path -Raw
    $obj = $raw | ConvertFrom-Json
    & $Mutator $obj
    $newRaw = ($obj | ConvertTo-Json -Depth 20)
    if ($raw.EndsWith("`n") -and -not $newRaw.EndsWith("`n")) {
        $newRaw += "`n"
    }
    return $newRaw
}

try {
    Write-Host "========================================" -ForegroundColor Cyan
    Write-Host "Update vcpkg Port: $Port -> $Version" -ForegroundColor Cyan
    Write-Host "========================================" -ForegroundColor Cyan
    Write-Host "Repository Root: $repoRoot" -ForegroundColor Gray
    if ($DryRun) {
        Write-Host "Mode: DRY RUN (no files written)" -ForegroundColor Yellow
    }
    Write-Host "========================================`n" -ForegroundColor Cyan

    # Step 1: Read current manifest, capture old version
    Write-Host "[1/4] Reading manifest..." -ForegroundColor Cyan
    if (-not (Test-Path -LiteralPath $manifestPath)) {
        throw "vcpkg.json not found at $manifestPath"
    }
    $manifest = Get-Content -LiteralPath $manifestPath -Raw | ConvertFrom-Json
    $override = $manifest.overrides | Where-Object { $_.name -eq $Port }
    if (-not $override) {
        throw "No override entry for '$Port' in $manifestPath. Add it to overrides[] manually first."
    }
    $result.OldVersion = $override.version
    Write-Host "  Current: $Port $($override.version)" -ForegroundColor White
    Write-Host "  Target : $Port $Version" -ForegroundColor White

    if ($override.version -eq $Version) {
        Write-Host "  ⊘ Version already matches; nothing to do." -ForegroundColor Yellow
        $result.Success = $true
        $result.Message = 'No changes; version already matches.'
        return $result
    }

    # Step 2: Compute new SHA512 if overlay port
    Write-Host "`n[2/4] Computing SHA512..." -ForegroundColor Cyan
    $isOverlay = Test-Path -LiteralPath $overlayPortDir
    if ($isOverlay) {
        $url = Get-PortDownloadUrl -Port $Port -Version $Version -Override $SourceUrl
        if (-not $url) {
            throw "No default download URL for port '$Port'. Provide -SourceUrl explicitly."
        }
        $result.Sha512 = Get-Sha512OfUrl -Url $url
        Write-Host "  SHA512: $($result.Sha512)" -ForegroundColor Green
    } else {
        Write-Host "  ⊘ Skipped (no overlay port for '$Port')" -ForegroundColor Yellow
    }

    # Step 3: Plan edits
    Write-Host "`n[3/4] Planning edits..." -ForegroundColor Cyan
    $edits = @()

    # 3a: top-level manifest override
    $newManifestRaw = Update-JsonFile -Path $manifestPath -Mutator {
        param($m)
        ($m.overrides | Where-Object { $_.name -eq $Port }).version = $Version
        if (-not [string]::IsNullOrWhiteSpace($Baseline)) {
            $m.'builtin-baseline' = $Baseline
        }
    }.GetNewClosure()
    $edits += @{ Path = $manifestPath; NewContent = $newManifestRaw }
    $result.FilesChanged += $manifestPath
    Write-Host "  • $manifestPath" -ForegroundColor White

    if ($isOverlay) {
        # 3b: overlay manifest version
        if (Test-Path -LiteralPath $overlayManifestPath) {
            $newOverlayRaw = Update-JsonFile -Path $overlayManifestPath -Mutator {
                param($m)
                $m.version = $Version
            }.GetNewClosure()
            $edits += @{ Path = $overlayManifestPath; NewContent = $newOverlayRaw }
            $result.FilesChanged += $overlayManifestPath
            Write-Host "  • $overlayManifestPath" -ForegroundColor White
        }

        # 3c: portfile.cmake SHA512 line
        if (Test-Path -LiteralPath $overlayPortfilePath) {
            $portfileText = Get-Content -LiteralPath $overlayPortfilePath -Raw
            $shaPattern = '(?m)^(\s*SHA512\s+)[0-9a-fA-F]+'
            if ([regex]::IsMatch($portfileText, $shaPattern)) {
                $newPortfile = [regex]::Replace($portfileText, $shaPattern, "`${1}$($result.Sha512)")
                $edits += @{ Path = $overlayPortfilePath; NewContent = $newPortfile }
                $result.FilesChanged += $overlayPortfilePath
                Write-Host "  • $overlayPortfilePath (SHA512)" -ForegroundColor White
            } else {
                $result.Errors += "Could not find a SHA512 line to update in $overlayPortfilePath"
            }
        }

        # 3d: libressl resource-file patch
        if ($Port -eq 'libressl' -and (Test-Path -LiteralPath $libresslPatchPath)) {
            $parts = $Version -split '\.'
            if ($parts.Count -lt 3) {
                $result.Errors += "LibreSSL version '$Version' must be in <major>.<minor>.<patch> form to update add-version-file.patch."
            } else {
                $major = $parts[0]; $minor = $parts[1]; $patch = $parts[2]
                $commaForm = "$major,$minor,$patch,0"
                $dotForm = "$major.$minor.$patch.0"
                $patchText = Get-Content -LiteralPath $libresslPatchPath -Raw

                $updated = $patchText
                $updated = [regex]::Replace($updated, '(?m)^(\+\s*FILEVERSION\s+)\d+,\d+,\d+,\d+', "`${1}$commaForm")
                $updated = [regex]::Replace($updated, '(?m)^(\+\s*PRODUCTVERSION\s+)\d+,\d+,\d+,\d+', "`${1}$commaForm")
                $updated = [regex]::Replace($updated, '("FileVersion",\s*")\d+\.\d+\.\d+\.\d+(")', "`${1}$dotForm`${2}")
                $updated = [regex]::Replace($updated, '("ProductVersion",\s*")\d+\.\d+\.\d+\.\d+(")', "`${1}$dotForm`${2}")

                if ($updated -ne $patchText) {
                    $edits += @{ Path = $libresslPatchPath; NewContent = $updated }
                    $result.FilesChanged += $libresslPatchPath
                    $result.LibresslPatchUpdated = $true
                    Write-Host "  • $libresslPatchPath (FileVersion -> $dotForm)" -ForegroundColor White
                    Write-Host "    NOTE: line offsets in this patch may also need adjustment after a major LibreSSL bump." -ForegroundColor Yellow
                } else {
                    Write-Host "  ⊘ $libresslPatchPath already at $dotForm" -ForegroundColor Yellow
                }
            }
        }
    }

    if (-not [string]::IsNullOrWhiteSpace($Baseline)) {
        Write-Host "  • vcpkg.json builtin-baseline -> $Baseline" -ForegroundColor White
    }

    # Step 4: Apply (or dry-run)
    Write-Host "`n[4/4] Writing changes..." -ForegroundColor Cyan
    if ($DryRun) {
        Write-Host "  ⊘ DryRun: no files written" -ForegroundColor Yellow
    } else {
        foreach ($edit in $edits) {
            Set-Content -LiteralPath $edit.Path -Value $edit.NewContent -NoNewline
            Write-Host "  ✓ Wrote $($edit.Path)" -ForegroundColor Green
        }
    }

    # Final
    Write-Host "`n========================================" -ForegroundColor Cyan
    Write-Host "UPDATE SUMMARY" -ForegroundColor Cyan
    Write-Host "========================================" -ForegroundColor Cyan
    $result.Success = ($result.Errors.Count -eq 0)
    if ($result.Success) {
        Write-Host "✓ Port ${Port}: $($result.OldVersion) -> $Version" -ForegroundColor Green
        Write-Host "  Files changed: $($result.FilesChanged.Count)" -ForegroundColor White
        foreach ($f in $result.FilesChanged) {
            Write-Host "    $f" -ForegroundColor Gray
        }
        Write-Host "`nNext steps:" -ForegroundColor White
        Write-Host "  1. Review the diff (git diff $opensshDir)." -ForegroundColor Gray
        Write-Host "  2. Validate: .\.github\tools\Install-VcpkgDependencies.ps1 -Clean" -ForegroundColor Gray
        Write-Host "  3. If vcpkg reports a rejected patch hunk, regenerate the patch from a fresh source extract." -ForegroundColor Gray
        Write-Host "  4. Build: .\.github\tools\Start-OpenSSHBuild.ps1" -ForegroundColor Gray
        $result.Message = "Bumped $Port from $($result.OldVersion) to $Version (DryRun=$DryRun)."
    } else {
        Write-Host "✗ UPDATE FAILED" -ForegroundColor Red
        foreach ($err in $result.Errors) {
            Write-Host "  • $err" -ForegroundColor Red
        }
        $result.Message = "$($result.Errors.Count) error(s) during update."
    }
    Write-Host ""

    return $result

} catch {
    Write-Host "`n========================================" -ForegroundColor Red
    Write-Host "ERROR" -ForegroundColor Red
    Write-Host "========================================" -ForegroundColor Red
    Write-Host $_.Exception.Message -ForegroundColor Red
    Write-Host $_.ScriptStackTrace -ForegroundColor Gray

    $result.Success = $false
    $result.Errors += "Tool error: $($_.Exception.Message)"
    $result.Message = "Update failed: $($_.Exception.Message)"
    return $result
}
