name: Sync Fork

on:
  schedule:
    - cron: '0 10 * * 1' # run every Monday morning
  workflow_dispatch: # on button click for debugging
  pull_request:

jobs:

  sync:
    runs-on: ubuntu-latest

    # outputs:
    #   output: ${{ steps.query.outputs.exists }}

    steps:
      - name: Check for Open Fork-Sync PRs
        id: query
        shell: pwsh 
        run: |
          $repo = $env:GITHUB_REPOSITORY
          Write-Host "repo: $repo"
          $response = (curl https://api.github.com/repos/$repo/pulls?state=open) | Out-String | ConvertFrom-Json
          $exists = $false
          ForEach ($title in $response.title) {
            if ($title.contains('Fork Sync')) {
              $exists = $true
            }
          }
          Write-Host "exists='$exists'"
          if ($exists -eq $true) {
            Write-Host "settings exists to true"
            echo "exists=true" >> "$env:GITHUB_OUTPUT"
          } 
          else {
            Write-Host "settings exists to false"
            echo "exists=false" >> "$env:GITHUB_OUTPUT"
          }
      - env:
          TEST1: ${{ steps.query.outputs.exists }}
        run: echo "val of test1 - $TEST1"
      - name: Run Fork-Sync
        if: steps.query.outputs.exists == 'false'
        uses: tgymnich/fork-sync@e2c7edd2fa70502b27eb4ff7644fe8709d1c71cb
        with:
          owner: openssh
          base: latestw_all
          head: master
          auto_approve: false
          ignore_fail: true
      
  # test:
  #   needs: check
  #   runs-on: ubuntu-latest
  #   steps:
  #     - run: echo "val of output var - ${{ needs.check.outputs.output }}"

  # sync:
  #   needs: check

  #   if: ${{ needs.check.outputs.output }} == 'false'

  #   runs-on: ubuntu-latest

  #   steps:

