name: Sync Fork

on:
  schedule:
    - cron: '0 10 * * 1' # run every Monday morning
  workflow_dispatch: # on button click for debugging
  pull_request:

jobs:

  check-for-existing-pr:
    runs-on: ubuntu-latest

    outputs:
      OPEN_FORK_SYNC_PR: ${{ steps.github-query.outputs.OPEN_FORK_SYNC_PR }}

    steps:
      - name: Check for Open Fork-Sync PRs
        id: github-query
        shell: pwsh 
        run: |
          $repo = $env:GITHUB_REPOSITORY
          Write-Host "repo: $repo"
          $response = (curl https://api.github.com/repos/$repo/pulls?state=open) | Out-String | ConvertFrom-Json
          $pr_exists = $false
          ForEach ($title in $response.title) {
            if ($title.contains('Fork Sync')) {
              $pr_exists = $true
            }
          }
          Write-Host "OPEN_FORK_SYNC_PR='$pr_exists'"
          if ($pr_exists -eq $true) {
            echo "OPEN_FORK_SYNC_PR='true'" >> $GITHUB_OUTPUT
          } 
          else {
            echo "OPEN_FORK_SYNC_PR='false'" >> $GITHUB_OUTPUT
          }
      - name: test 1
        run: echo "var set to ${{ steps.check-for-existing-pr.outputs.OPEN_FORK_SYNC_PR }}"
      - name: test 2
        run: echo "var set to ${{ steps.github-query.outputs.OPEN_FORK_SYNC_PR }}"
  test:
    needs: check-for-existing-pr
    runs-on: ubuntu-latest
    steps:
      - run: echo "val of output var - ${{ needs.check-for-existing-pr.outputs.OPEN_FORK_SYNC_PR }}"

  sync:
    needs: check-for-existing-pr

    if: ${{ needs.check-for-existing-pr.outputs.OPEN_FORK_SYNC_PR == 'false' }}

    runs-on: ubuntu-latest

    steps:
      - name: Run Fork-Sync
        uses: tgymnich/fork-sync@e2c7edd2fa70502b27eb4ff7644fe8709d1c71cb
        with:
          owner: openssh
          base: latestw_all
          head: master
          auto_approve: false
          ignore_fail: true
